### ISSUE TITLE
How do the solution for day12 work?

### ISSUE THREAD

**Issue by MattiaCacciatore** [Rtchaik/AoC-2021#1]
just...how? and why?
it's so efficient. It seems to be deterministic but it's not. It doesn't generate duplicate paths and it gets the right answer in less than 1 seconds. HOW?

**Comment by Rtchaik** [comment]
In part 1 I'm using recursion to visit all available points. As the travel history is kept in PATH, I visit small point 1 time only and big points without limitations. So I'm just following the rules.

In part 2 the approach is similar with small update. I'm visiting all points without limits until visiting the small one the second time. At this moment the rules return to the same as part 1, so the last part of this branch is moved to part 1 calculation. I suppose you are confused with this part of the part2 solution:
`(part2,part1)[point.islower() and point in path](data, path + [point])`
Here I use an interesting feature of python where bool in fact is int 0 or 1. So bool condition returns index for choosing the function to continue the recursive call.

If you need more deep comment in some aspects of the code please let me know.
